import Layout from '@/components/Layout';
import { AdminHeader,AdminPagination,AdminError } from '@/components/AdminTools';
import { useAdminTable } from '@/lib/use-admin-table';
import type { PaymentRow } from '@/lib/payments';
const labels:Record<string,string>={pending:'En attente',held:'En attente de libération',released:'Libéré',refunded:'Remboursé',failed:'Échec',disputed:'En litige'};
export default function AdminPayments(){
 const state=useAdminTable<PaymentRow>('payments','id,order_id,client_id,provider_id,amount,commission_amount,total_amount,currency,status,gateway,gateway_transaction_id,created_at','status');
 return <Layout title="Paiements"><div className="mx-auto max-w-3xl"><AdminHeader title="Registre des paiements" description="Suivi des paiements de services et des litiges" busy={state.loading} refresh={state.refresh} /><p className="mb-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm">Ce registre montre les états enregistrés dans LOBOKO. Sans confirmation d’un prestataire de paiement, un état ne prouve pas un encaissement ou un remboursement réel. Les remboursements automatiques ne sont pas encore disponibles.</p><label className="mb-4 block text-sm">État du paiement<select value={state.filter} onChange={e=>state.setFilter(e.target.value)} className="ml-2 rounded-xl border border-[var(--loboko-border)] bg-[var(--loboko-surface)] px-3 py-3 text-base"><option value="all">Tous</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 {state.failed?<AdminError retry={state.refresh} />:state.loading?<p role="status">Chargement…</p>:<div className="space-y-3">{!state.rows.length&&<p>Aucun paiement pour ce filtre.</p>}{state.rows.map(row=><article key={row.id} className="rounded-2xl border border-[var(--loboko-border)] bg-[var(--loboko-surface)] p-4"><div className="flex justify-between gap-2"><strong>{Number(row.total_amount).toLocaleString('fr-FR')} {row.currency}</strong><span className="text-sm">{labels[row.status]??row.status}</span></div><p className="mt-1 text-xs">Service : {Number(row.amount).toLocaleString('fr-FR')} {row.currency} · Commission : {Number(row.commission_amount).toLocaleString('fr-FR')} {row.currency}</p><dl className="mt-3 space-y-1 break-all text-xs text-[var(--loboko-text-secondary)]"><div>Référence : {row.id}</div><div>Commande : {row.order_id}</div><div>Client : {row.client_id}</div><div>Prestataire : {row.provider_id}</div><div>Prestataire de paiement : {row.gateway||'Aucun renseigné'}</div><div>Transaction externe : {row.gateway_transaction_id||'Aucune référence'}</div><div>{new Date(row.created_at).toLocaleString('fr-FR')}</div></dl></article>)}</div>}
 <AdminPagination page={state.page} total={state.total} busy={state.loading||state.failed} onChange={state.setPage} /></div></Layout>;
}
