import { useEffect, useState, type FormEvent } from 'react';
import Layout from '@/components/Layout';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase';
import { useAdminTable } from '@/lib/use-admin-table';
import { AdminHeader,AdminPagination,AdminError,AdminDialog } from '@/components/AdminTools';
import { toast } from 'sonner';
interface Campaign {id:string;title:string;description:string;image_url:string;category_slug:string;active:boolean;sort_order:number;starts_at:string|null;ends_at:string|null;created_at:string;}
interface Category {name:string;slug:string;}
const empty={title:'',description:'',image_url:'',category_slug:'',active:false,sort_order:0,starts_at:'',ends_at:''};
const localDate=(date:string|null)=>{if(!date)return '';const value=new Date(date);return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function AdminAds(){
 const {user}=useAuth();const state=useAdminTable<Campaign>('loboko_ad_campaigns','id,title,description,image_url,category_slug,active,sort_order,starts_at,ends_at,created_at');
 const [editing,setEditing]=useState<Campaign|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[categories,setCategories]=useState<Category[]>([]),[categoryError,setCategoryError]=useState(false);
 useEffect(()=>{let cancelled=false;void(async()=>{const result=await supabase.from('service_categories').select('name,slug').eq('is_active',true).order('name');if(cancelled)return;if(result.error)setCategoryError(true);else setCategories((result.data??[]) as Category[]);})();return()=>{cancelled=true;};},[]);
 const edit=(row:Campaign|null)=>{setEditing(row);setForm(row?{title:row.title,description:row.description,image_url:row.image_url,category_slug:row.category_slug,active:row.active,sort_order:row.sort_order,starts_at:localDate(row.starts_at),ends_at:localDate(row.ends_at)}:{...empty,category_slug:categories[0]?.slug??''});setOpen(true);};
 const save=async(event:FormEvent)=>{event.preventDefault();if(busy||!user)return;if(!form.image_url.startsWith('https://')){toast.error('Choisissez un lien d’image HTTPS.');return;}if(form.starts_at&&form.ends_at&&new Date(form.ends_at)<=new Date(form.starts_at)){toast.error('La fin doit être après le début.');return;}setBusy(true);try{const values={...form,title:form.title.trim(),description:form.description.trim(),image_url:form.image_url.trim(),starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,ends_at:form.ends_at?new Date(form.ends_at).toISOString():null};const result=editing?await supabase.from('loboko_ad_campaigns').update(values).eq('id',editing.id).select('id').single():await supabase.from('loboko_ad_campaigns').insert({...values,created_by:user.id}).select('id').single();if(result.error)throw result.error;toast.success('Campagne enregistrée');setOpen(false);state.refresh();}catch{toast.error('Enregistrement impossible. Vérifiez les champs et réessayez.');}finally{setBusy(false);}};
 const toggle=async(row:Campaign)=>{if(busy)return;if(!confirm(row.active?'Désactiver cette campagne dans l’accueil ?':'Activer cette campagne selon ses dates de diffusion ?'))return;setBusy(true);try{const result=await supabase.from('loboko_ad_campaigns').update({active:!row.active}).eq('id',row.id).select('id').single();if(result.error)throw result.error;toast.success('Diffusion mise à jour');state.refresh();}catch{toast.error('Modification impossible. Réessayez.');}finally{setBusy(false);}};
 const input='mt-1 w-full rounded-xl border border-[var(--loboko-border)] bg-[var(--loboko-bg)] px-3 py-3 text-base';
 return <Layout title="Publicités"><div className="mx-auto max-w-3xl"><AdminHeader title="Publicités" description="Campagnes affichées dans le carrousel de l’accueil" busy={state.loading} refresh={state.refresh} /><button type="button" disabled={busy} onClick={()=>edit(null)} className="mb-4 rounded-xl bg-[#2563eb] px-4 py-3 text-sm font-semibold text-white">Créer une campagne</button>
 {state.failed?<AdminError retry={state.refresh} />:state.loading?<p role="status">Chargement…</p>:<div className="space-y-3">{!state.rows.length&&<p>Aucune campagne.</p>}{state.rows.map(row=><article key={row.id} className="rounded-2xl border border-[var(--loboko-border)] bg-[var(--loboko-surface)] p-4"><div className="flex gap-3"><img src={row.image_url} alt="" loading="lazy" className="h-20 w-28 rounded-xl object-cover" /><div className="min-w-0"><h2 className="font-semibold">{row.title}</h2><p className="mt-1 text-xs text-[var(--loboko-text-secondary)]">{row.active?'Activée':'Désactivée'} · Ordre {row.sort_order}</p><p className="mt-1 text-xs">{row.starts_at?new Date(row.starts_at).toLocaleString('fr-FR'):'Sans date de début'} → {row.ends_at?new Date(row.ends_at).toLocaleString('fr-FR'):'Sans date de fin'}</p></div></div><div className="mt-3 flex gap-2"><button type="button" disabled={busy} onClick={()=>edit(row)} className="rounded-lg border border-[var(--loboko-border)] px-3 py-2 text-sm disabled:opacity-50">Modifier</button><button type="button" disabled={busy} onClick={()=>toggle(row)} className="rounded-lg border border-[var(--loboko-border)] px-3 py-2 text-sm disabled:opacity-50">{row.active?'Désactiver':'Activer'}</button></div></article>)}</div>}
 <AdminPagination page={state.page} total={state.total} busy={state.loading||state.failed} onChange={state.setPage} />
 <AdminDialog open={open} title={editing?'Modifier la campagne':'Créer une campagne'} busy={busy} onClose={()=>setOpen(false)}><form onSubmit={save} className="space-y-3"><label className="block text-sm">Titre<input className={input} required maxLength={120} value={form.title} disabled={busy} onChange={e=>setForm({...form,title:e.target.value})} /></label><label className="block text-sm">Description<textarea className={input} maxLength={400} value={form.description} disabled={busy} onChange={e=>setForm({...form,description:e.target.value})} /></label><label className="block text-sm">Image (lien HTTPS)<input className={input} type="url" required value={form.image_url} disabled={busy} onChange={e=>setForm({...form,image_url:e.target.value})} /></label><label className="block text-sm">Catégorie à ouvrir<select className={input} required value={form.category_slug} disabled={busy} onChange={e=>setForm({...form,category_slug:e.target.value})}><option value="">Choisir une catégorie</option>{form.category_slug&&!categories.some(c=>c.slug===form.category_slug)&&<option value={form.category_slug}>{form.category_slug}</option>}{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label>{categoryError&&<p role="alert" className="text-xs">Impossible de charger les catégories. Fermez puis actualisez cette page.</p>}<label className="block text-sm">Ordre d’affichage (plus petit en premier)<input className={input} type="number" required min={-10000} max={10000} value={form.sort_order} disabled={busy} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})} /></label><label className="block text-sm">Début (facultatif)<input className={input} type="datetime-local" value={form.starts_at} disabled={busy} onChange={e=>setForm({...form,starts_at:e.target.value})} /></label><label className="block text-sm">Fin (facultative)<input className={input} type="datetime-local" value={form.ends_at} disabled={busy} onChange={e=>setForm({...form,ends_at:e.target.value})} /></label><p className="text-xs text-[var(--loboko-text-secondary)]">Les dates utilisent l’heure de votre appareil. Une campagne activée s’affiche uniquement pendant sa période de diffusion.</p><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.active} disabled={busy} onChange={e=>setForm({...form,active:e.target.checked})} />Activer la diffusion</label><div className="flex justify-end gap-3"><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Annuler</button><button type="submit" disabled={busy} className="rounded-xl bg-[#2563eb] px-4 py-3 text-white disabled:opacity-50">{busy?'Enregistrement…':'Enregistrer'}</button></div></form></AdminDialog>
 </div></Layout>;
}
