import Layout from '@/components/Layout';
import { Link } from 'react-router-dom';
import { AdminHeader,AdminPagination,AdminError } from '@/components/AdminTools';
import { useAdminTable } from '@/lib/use-admin-table';
import { ADMIN_ACTION_LABELS } from '@/lib/admin-controls';
interface Entry {id:string;admin_id:string;target_user_id:string|null;action_type:string;reason:string|null;created_at:string;target_type:string|null;target_id:string|null;details:Record<string,unknown>|null;}
export default function AdminJournal(){
 const state=useAdminTable<Entry>('admin_actions','id,admin_id,target_user_id,action_type,reason,created_at,target_type,target_id,details');
 return <Layout title="Journal administrateur"><div className="mx-auto max-w-3xl"><AdminHeader title="Journal des actions" description="Historique des décisions administratives, en lecture seule" busy={state.loading} refresh={state.refresh} />{state.failed?<AdminError retry={state.refresh} />:state.loading?<p role="status">Chargement…</p>:<div className="space-y-3">{!state.rows.length&&<p>Aucune action enregistrée.</p>}{state.rows.map(row=><article key={row.id} className="rounded-2xl border border-[var(--loboko-border)] bg-[var(--loboko-surface)] p-4"><strong>{ADMIN_ACTION_LABELS[row.action_type]??row.action_type}</strong><p className="mt-1 text-xs text-[var(--loboko-text-secondary)]">{new Date(row.created_at).toLocaleString('fr-FR')}</p><p className="mt-2 text-sm whitespace-pre-wrap">{row.reason||'Aucun motif enregistré'}</p><div className="mt-2 space-y-1 break-all text-xs"><p>Admin : <Link className="text-[#60a5fa]" to={`/u/${row.admin_id}`}>{row.admin_id}</Link></p>{row.target_user_id&&<p>Compte concerné : <Link className="text-[#60a5fa]" to={`/u/${row.target_user_id}`}>{row.target_user_id}</Link></p>}{row.target_id&&<p>Cible : {row.target_type} · {row.target_id}</p>}</div>{row.details&&<details className="mt-3 text-xs"><summary className="cursor-pointer">Détails de la décision</summary><pre className="mt-2 overflow-x-auto rounded-xl bg-[var(--loboko-bg)] p-3">{JSON.stringify(row.details,null,2)}</pre></details>}</article>)}</div>}<AdminPagination page={state.page} total={state.total} busy={state.loading||state.failed} onChange={state.setPage} /></div></Layout>;
}
