project_id = "loboko-app"

[functions.payment-checkout]
verify_jwt = true

[functions.payment-status]
verify_jwt = true

[functions.cinetpay-checkout]
verify_jwt = true

[functions.cinetpay-status]
verify_jwt = true

[functions.cinetpay-notify]
verify_jwt = true
